# ===============================
# Application
# ===============================
spring.application.name=feedback_server


# ===============================
# MongoDB
# ===============================
spring.mongodb.uri=mongodb+srv://tarapadagarai23:z08tarapadalP23@cluster0.821xo.mongodb.net/feedbackDB
spring.data.mongodb.auto-index-creation=true


# ===============================
# OAuth2 - Google
# ===============================
spring.security.oauth2.client.registration.google.client-id=35904192488-klsl2aj7tgrq9lecldfij1p412qbf5ii.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# ===============================
# JWT
# ===============================
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y
